### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by e135193** [RFDesign/SiK_Multipoint#1]
I'm getting compilation error

     CC radio/mavlink.c
     radio/mavlink.c:131: error 158: overflow in implicit constant conversion
     include/rules.mk:100: recipe for target 'obj/rfd900a/radio~rfd900a/mavlink.rel' failed
     make[1]: *** [obj/rfd900a/radio~rfd900a/mavlink.rel] Error 1
     make[1]: Leaving directory '/home/voyvoda/Desktop/SiK_Multipoint-master/Firmware'
     Makefile:96: recipe for target 'build~radio~rfd900a' failed
     make: *** [build~radio~rfd900a] Error 2

**Comment by lhovo** [comment]
Are you able to give any more information on your build environment like the version number?
Is the base SiK compiling for you?

**Comment by e135193** [comment]
Hello, I am usign ubuntu 18.04 and I can properly compile the base Sik firmware.

**Comment by lhovo** [comment]
AES encryption is done at the hardware layer, so the first thing you need to have is a board with the AES encryption.

It has been a long time since I looked at the code that uses AES encryption.
I believe it's not fully operational as it presently stands. The problem was the speed of the encryption and decryption caused delays in receiving / transmitting causing the two modems to loose sync and they hop through the frequencies.

Have a go if you like, but don't expect it to work perfectly out of the box. Prepare to read the code and make improvements.

The setting of the encryption key is done in the parameters.c file, have a dig through this and see if you can see where this is set.

Due to AES not fully working to the level I would like, it had become a undocumented feature waiting for someone to improve the code.

If your willing to put in the time and effort to improving the code you could be the first to get this to work.

Otherwise I would recommend purchasing the ARM version that has a lot more power to beable to do the encryption on the fly.
